#!/bin/bash

entries="⇠ Reset session\n⏾ Scegli attività\n⭮ Modifica manualmente"

selected=$(echo -e $entries|wofi --width 250 --height 210 --dmenu --cache-file /dev/null | awk '{print tolower($2)}')

# echo "$selected"
case $selected in
  reset)
    $ONEDRIVE/dotfiles/survey/bin/reset_session;;
  scegli)
    $ONEDRIVE/dotfiles/survey/bin/choose_mod;;
  modifica)
    $ONEDRIVE/dotfiles/survey/bin/manual_mod;;
esac
