#!/usr/bin/env bash

bin_path=~/.local/share/survey/bin/

entries="⇠ Reset session\n⏾ Scegli attività\n⭮ Modifica manualmente\nImposta Submit Rating\nOpen Guidelines\nMonthly Statement"

selected=$(echo -e $entries|wofi --width 250 --height 210 --dmenu --cache-file /dev/null | awk '{print tolower($2)}')

# echo "$selected"
case $selected in
  reset)
    $bin_path/reset_session;;
  scegli)
    $bin_path/choose_mod;;
  modifica)
    $bin_path/manual_mod;;
  submit)
    $bin_path/set_button.sh;;
  guidelines)
    $bin_path/choose_guidelines.sh;;
  statement)
    $bin_path/month_hours.sh;;
esac
